name: moments
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.4.4
  connectivity_plus: ^1.4.0
  cupertino_icons: ^1.0.0
  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  flutter:
    sdk: flutter
  flutter_login_facebook: ^1.1.0
  flutter_signin_button: ^2.0.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.9

  get: ^4.6.1
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.7
  http: ^0.13.3
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.7
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/ring.svg

  fonts:
    - family: KyivType Sans
      fonts:
        - asset: assets/fonts/KyivType Sans Regular-.otf
          #weight: 400
        - asset: assets/fonts/KyivType Sans Bold-.otf
          #weight: 700

    - family: Vollkorn
      fonts:
        - asset: assets/fonts/VollkornRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/VollkornRomanBold.ttf
          weight: 700
    - family: Assistant
      fonts:
        - asset: assets/fonts/AssistantRegular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Mulish
      fonts:
        - asset: assets/fonts/MulishSemiBold.ttf
          weight: 600
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
